---
# tasks file for roles/config_ipres, configure Cluster VIP for the cluster as a resource

- name: Create IP resource
  shell: pcs resource create ClusterVIP ocf:heartbeat:IPaddr2 ip={{ clustervip }} cidr_netmask=24 op monitor interval=30s && touch create-ip.txt
  args:
          creates: create-ip.txt
  when: inventory_hostname in groups['clusteradmin']

