---
# tasks file for roles/init-env. Install all needed software, and create the mount point to use to store PC2 profiles. Also transfer all necessary files needed such as PC2 package, and the PC2 resource agent
- name: Adding DRBD repo
  ansible.builtin.apt_repository:
          repo: ppa:linbit/linbit-drbd9-stack
          update_cache: yes
          state: present

- name: Install required packages
  ansible.builtin.package:
          name: 
           - unzip 
           - drbd-utils
           - drbd-dkms 
           - default-jre 
           - pacemaker 
           - corosync 
           - pcs 
           - wget
          state: present

##Task executed only for ubuntu >= 22
- name: Install resource agents package 
  ansible.builtin.package:
          name:
                  - resource-agents
          state: present
  when: "{{ ansible_distribution_major_version }} >= 22"

- name: Create mount point
  ansible.builtin.file:
          path: /pc2data
          state: directory
          mode: '0777'
              
- name: Transfer PC2 agent file
  copy:
          src: "files/{{ resourceagent }}"
          dest: /usr/lib/ocf/resource.d/heartbeat/
          mode: '0755'

- name: Transfer and unzip PC2 archive
  ansible.builtin.unarchive:
          src: "files/{{ pc2file }}"
          dest: /usr/local

- name: Create a softlink to PC2 installation directory
  ansible.builtin.file:
          src: /usr/local/pc2-9.9build
          dest: /usr/local/pc2
          state: link
